Repository WildCodeSchool-2024-02/JS-RMT-julien-TeamA-Project2, pull requests merged in 2024-05, with the labels that each got.

#1 Lancement
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/main.jsx
  server/app/router.js
  server/database/data.js
Labels: REVIEWED

#2 @feat/dispaly movies
  client/src/App.css
  client/src/App.jsx
  client/src/assets/styles/components/MovieCard.css
  client/src/components/MovieCard.jsx
  client/src/main.jsx
  server/app/router.js
Labels: REVIEWED

#4 @feat/create context
  client/.eslintrc.json
  client/src/contexts/FavContext.jsx
  client/src/main.jsx
Labels: CORRECTIONS DONE, REVIEWED

#3 Add favorites
  client/src/assets/favicon.ico
  client/src/assets/images/background.webp
  client/src/assets/images/logo.png
  client/src/assets/styles/components/line-movie-item.css
  client/src/assets/styles/pages/favorites.css
  client/src/components/LineMovieItem.jsx
  client/src/components/LineMovieList.jsx
  client/src/main.jsx
  client/src/pages/FavoritesPage.jsx
Labels: REVIEW REQUESTED

#7 @feat/fix-app
  client/src/App.jsx
Labels: REVIEWED

#5 @feat/contact form
  client/package.json
  client/src/App.css
  client/src/assets/styles/ContactForm.css
  client/src/components/ContactForm.jsx
  client/src/main.jsx
  client/src/pages/ContactPage.jsx
Labels: REVIEWED

#6 @feat/information movies
  client/src/App.css
  client/src/components/MovieDescription.css
  client/src/components/MovieDescription.jsx
  client/src/components/MoviePoster.css
  client/src/components/MoviePoster.jsx
  client/src/main.jsx
  client/src/pages/MoviePage.css
  client/src/pages/Moviepage.jsx
  server/app/router.js
Labels: REVIEWED

#8 Init SQL
  client/src/main.jsx
  server/app/router.js
  server/database/data.js
  server/database/schema.sql
Labels: REVIEW REQUESTED

#10 @hotfix/path env url
  client/src/main.jsx
  client/src/pages/ErrorPage.jsx
Labels: REVIEWED
